import {
  Activity,
  Archive,
  BarChart3,
  Blocks,
  BookOpenText,
  Bot,
  Boxes,
  Braces,
  BrainCircuit,
  BriefcaseBusiness,
  CalendarClock,
  ChartNoAxesCombined,
  CheckCheck,
  CircleGauge,
  ClipboardCheck,
  Cloud,
  Code2,
  Component,
  Database,
  DraftingCompass,
  Eye,
  FileClock,
  FileCode2,
  FileJson,
  FilePenLine,
  FileStack,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  FolderKanban,
  GitCompareArrows,
  GitPullRequest,
  Globe2,
  History,
  KeyRound,
  Languages,
  LayoutDashboard,
  Library,
  Lightbulb,
  Link2,
  ListChecks,
  LockKeyhole,
  Map,
  Megaphone,
  Merge,
  MessageSquareText,
  Network,
  PackageOpen,
  PanelTop,
  Plug,
  RadioTower,
  RefreshCcw,
  Rocket,
  Route,
  ScanSearch,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Split,
  Tags,
  Target,
  TestTubes,
  TimerReset,
  TrendingUp,
  Undo2,
  UserCheck,
  UserCog,
  Users,
  UsersRound,
  Variable,
  Webhook,
  Workflow,
  Zap,
} from "lucide-react";

// Workspace navigation mirrors the full Content OS feature taxonomy so every
// product area is visible before its dedicated screen is implemented.
export const workspaceNav = [
  {
    title: "Overview",
    icon: LayoutDashboard,
  },
  {
    title: "Content",
    icon: BookOpenText,
    subItems: [
      { title: "All Content", icon: Library },
      { title: "Drafts", icon: FilePenLine },
      { title: "Pages", icon: PanelTop },
      { title: "Collections", icon: FolderKanban },
      { title: "Assets", icon: PackageOpen },
      { title: "Content Slots", icon: Blocks },
      { title: "Scheduled", icon: CalendarClock },
      { title: "Archived", icon: Archive },
    ],
  },
  {
    title: "Architecture",
    icon: DraftingCompass,
    subItems: [
      { title: "Content Types", icon: FileJson },
      { title: "Field Schemas", icon: Braces },
      { title: "Reusable Blocks", icon: Component },
      { title: "References", icon: Link2 },
      { title: "Validation Rules", icon: CheckCheck },
      { title: "Taxonomies", icon: Tags },
      { title: "Localization", icon: Languages },
      { title: "External Sources", icon: Database },
    ],
  },
  {
    title: "Editorial",
    icon: FileText,
    subItems: [
      { title: "Structured Editor", icon: FilePenLine },
      { title: "Visual Editor", icon: Eye },
      { title: "Comments & Mentions", icon: MessageSquareText },
      { title: "Assignments", icon: UserCheck },
      { title: "Review Queue", icon: ClipboardCheck },
      { title: "Approval Workflows", icon: Workflow },
      { title: "Version History", icon: History },
      { title: "Compare & Rollback", icon: GitCompareArrows },
      { title: "Bulk Editing", icon: FileStack },
      { title: "AI Assistant", icon: Sparkles },
    ],
  },
  {
    title: "Publishing",
    icon: Rocket,
    subItems: [
      { title: "Publishing Queue", icon: ListChecks },
      { title: "Releases", icon: Boxes },
      { title: "Environments", icon: Cloud },
      { title: "Delivery APIs", icon: RadioTower },
      { title: "Webhooks", icon: Webhook },
      { title: "Edge Delivery", icon: Zap },
      { title: "Cache Invalidation", icon: RefreshCcw },
      { title: "Publishing History", icon: FileClock },
      { title: "Sites & Brands", icon: Globe2 },
    ],
  },
  {
    title: "Governance",
    icon: ShieldCheck,
    subItems: [
      { title: "Team & Members", icon: Users },
      { title: "Roles", icon: UserCog },
      { title: "Permissions", icon: LockKeyhole },
      { title: "Content Policies", icon: ClipboardCheck },
      { title: "Consent & Privacy", icon: Fingerprint },
      { title: "Audit Logs", icon: FileClock },
      { title: "Data Residency", icon: Map },
      { title: "Retention Policies", icon: TimerReset },
      { title: "SSO & SCIM", icon: KeyRound },
    ],
  },
  {
    title: "Developers",
    icon: Code2,
    subItems: [
      { title: "API Explorer", icon: FileCode2 },
      { title: "REST API", icon: Braces },
      { title: "GraphQL API", icon: Network },
      { title: "SDKs & CLI", icon: Code2 },
      { title: "Type Generation", icon: Variable },
      { title: "Preview Tools", icon: Eye },
      { title: "API Tokens", icon: KeyRound },
      { title: "Service Accounts", icon: UserCog },
      { title: "Apps & Plugins", icon: Plug },
      { title: "Logs & Usage", icon: Activity },
      { title: "Import & Export", icon: Merge },
    ],
  },
  {
    title: "Audiences",
    icon: UsersRound,
    subItems: [
      { title: "Profiles", icon: Users },
      { title: "Anonymous Visitors", icon: Fingerprint },
      { title: "Identity Resolution", icon: Merge },
      { title: "Traits", icon: Tags },
      { title: "Calculated Attributes", icon: Variable },
      { title: "Behavior Events", icon: Activity },
      { title: "Segments", icon: Filter },
      { title: "Consent State", icon: ShieldCheck },
      { title: "Profile History", icon: History },
      { title: "Data Connections", icon: Plug },
    ],
  },
  {
    title: "Personalization",
    icon: Target,
    subItems: [
      { title: "Content Variants", icon: Split },
      { title: "Targeting Rules", icon: SlidersHorizontal },
      { title: "Segment Targeting", icon: UsersRound },
      { title: "Context Targeting", icon: Route },
      { title: "Component Targeting", icon: Component },
      { title: "Behavior Targeting", icon: Activity },
      { title: "Edge Decisions", icon: Zap },
      { title: "Frequency Caps", icon: CircleGauge },
      { title: "Boosts & Exclusions", icon: Flag },
      { title: "Topic Journey Stages", icon: Map },
    ],
  },
  {
    title: "Experiments",
    icon: TestTubes,
    subItems: [
      { title: "All Experiments", icon: TestTubes },
      { title: "A/B Tests", icon: Split },
      { title: "Traffic Allocation", icon: GitPullRequest },
      { title: "Goals & Metrics", icon: Target },
      { title: "Holdout Groups", icon: UsersRound },
      { title: "Eligibility Rules", icon: CheckCheck },
      { title: "Experiment Schedule", icon: CalendarClock },
      { title: "Results", icon: BarChart3 },
      { title: "Winner Suggestions", icon: Lightbulb },
      { title: "Multi-armed Bandits", icon: Bot },
      { title: "Collision Control", icon: ShieldCheck },
    ],
  },
  {
    title: "Recommendations",
    icon: BrainCircuit,
    subItems: [
      { title: "Recommendation Models", icon: BrainCircuit },
      { title: "Similar Content", icon: ScanSearch },
      { title: "User Affinity", icon: UserCheck },
      { title: "Trending Content", icon: TrendingUp },
      { title: "Content-based Ranking", icon: FileStack },
      { title: "Collaborative Ranking", icon: UsersRound },
      { title: "Context-aware Ranking", icon: Route },
      { title: "Diversity Controls", icon: SlidersHorizontal },
      { title: "Business Rules", icon: BriefcaseBusiness },
      { title: "Real-time Ranking", icon: Zap },
    ],
  },
  {
    title: "Intelligence",
    icon: ChartNoAxesCombined,
    subItems: [
      { title: "Content Performance", icon: BarChart3 },
      { title: "Audience Performance", icon: UsersRound },
      { title: "Funnels & Journeys", icon: Route },
      { title: "Topic Interest", icon: TrendingUp },
      { title: "Semantic Search", icon: Search },
      { title: "AI Tag Suggestions", icon: Sparkles },
      { title: "Embeddings", icon: BrainCircuit },
      { title: "Duplicate Detection", icon: GitCompareArrows },
      { title: "Content Gaps", icon: ScanSearch },
      { title: "Knowledge Graph", icon: Network },
      { title: "Decision Explanations", icon: Lightbulb },
    ],
  },
  {
    title: "Settings",
    icon: Settings,
    subItems: [
      { title: "General", icon: Settings },
      { title: "Workspace", icon: BriefcaseBusiness },
      { title: "Branding", icon: Megaphone },
      { title: "Integrations", icon: Plug },
      { title: "Security", icon: ShieldCheck },
      { title: "Billing & Plans", icon: CircleGauge },
    ],
  },
];
